esphome:
  name: mq_node

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf

wifi:
  ssid: "<Network-SSID>"
  password: "<Network-PW>"

logger:

mqtt:
  broker: "<Broker-IP>"
  topic_prefix: iot/mq

sensor:
  - platform: adc
    pin: <GPIOX>
    name: "Gas Sensor"
    update_interval: 5s
